### ISSUE TITLE
Registrierung

### ISSUE THREAD

**Issue by lerchl** [YusTheYokai/appointment-finder#1]
**User Story**
Als User möchte ich mich mit einem Nutzernamen und Passwort registrieren um neue Posts zu erstellen und für Zeiten zu voten.

**Akzeptanzkriterien**
- Es gibt eine Registration mit Eingabefeldern für Nutzername, Vorname, Nachname, Passwort und Passwort wiederholen, alle Felder sind required
- ein Nutzername ist mindestens 3 und maximal 30 Zeichen lang
- ein Vorname ist mindestens 2 und maximal 30 Zeichen lang
- ein Nachname ist mindestens 2 und maximal 30 Zeichen lang
- ein Passwort ist mindestens 8 und maximal 50 Zeichen lang
- Passwort und Passwort wiederholen müssen identisch sein
- Nutzernamen sind unique
- Bei Fehlern wie einem nicht übereinstimmendem Passwort oder bereits verwendetem Nutzernamen gibt es entsprechende Fehlermeldungen

**Comment by YusTheYokai** [comment]
irrelevant

**Comment by lerchl** [comment]
irrelevant
